version: "3"
services:
  haproxy:
    hostname: haproxy
    image: bjoernbessert/haproxy-cert-otf
    volumes:
      - ./lua_files:/etc/haproxy/lua_files
    depends_on:
      - apache
      - ca-api
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - GET_CERT_METHOD=${GET_CERT_METHOD:-localca}
      - HOST_INTERNAL_CA=internal-ca.example.local
      #- GET_CERT_METHOD=localca
      #- GET_CERT_METHOD=http
    extra_hosts:
      - "internal-ca.example.local:172.17.0.1"
  apache:
    hostname: apache
    image: bjoernbessert/apache-cert-otf
  ca-api:
    hostname: ca-api
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./ca-api-example/app:/app
    ports:
      - "8081:80"
      - "8443:443"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=80
