name: haproxy-cert-otf CI

#on: [push]
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '30 23 * * *'

jobs:
  build_01:
    #runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-18.04
    env:
       UBUNTU_DOCKER_IMAGE: ${{ matrix.UBUNTU_DOCKER_IMAGE }}
       HAPROXY_MAIN_VERSION: ${{ matrix.HAPROXY_MAIN_VERSION }}
    strategy:
      matrix:
        include:
          - UBUNTU_DOCKER_IMAGE: "ubuntu:20.04"
            HAPROXY_MAIN_VERSION: "2.4"
#          - UBUNTU_DOCKER_IMAGE: "ubuntu:18.04"
#            HAPROXY_MAIN_VERSION: "2.4"
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Debug-Output
        run: echo $UBUNTU_DOCKER_IMAGE $HAPROXY_MAIN_VERSION

      - name: Install bats
        run: sudo apt-get update && sudo apt-get -y install bats

      - name: Show bats version
        run: bats -v

      - name: Build apache dockerimage
        run: make build-without-cache
        working-directory: ./dockerfiles/apache

      - name: Build haproxy dockerimage
        run: make build-without-cache
        working-directory: ./dockerfiles/haproxy

      - name: Execute testsuite
        run: make test

      - name: Show Debug-Log
        if: ${{ always() }}
        run: cat /tmp/debug.log

      - name: Cleanup
        run: make clean
